class-factory: Fix toString for overloaded methods
frida/frida-java-bridge pull request #272
Opened 2022-10-29 18:55 UTC by yotamN

2023-01-27 19:51 UTC, oleavr requested changes
Thanks! Only one style issue and this should be good to merge:

2023-01-27 19:51 UTC, oleavr commented on lib/class-factory.js
> +          return `<class: ${receiver.$n}>`;
Indentation should be two spaces.

2023-01-27 19:54 UTC, yotamN commented on lib/class-factory.js
> +          return `<class: ${receiver.$n}>`;
Fixed

2023-04-14 11:21 UTC, merged

2023-04-14 11:21 UTC, oleavr commented
Thanks! 🙌